services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: boilerplate-server
    container_name: ${PROJECT_NAME}-server
    restart: unless-stopped
    env_file: .env
    ports:
      - "${SERVER_PORT}:3001"
    volumes:
      - .:/home/node/app
      # A LINHA ABAIXO É O TRUQUE:
      # Sem os dois pontos (:), isso diz ao Docker para ignorar o que está no host 
      # e usar a pasta node_modules que foi criada dentro da imagem durante o build.
      - /home/node/app/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  # O volume 'node_modules' foi removido daqui pois agora é anônimo dentro do serviço server